/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by Sitio auto-import components plugin
declare module "@components/*" {
  import type { Component } from "svelte";
  const component: Component<any>;
  export default component;
}
declare module "@shared/*" {
  import type { Component } from "svelte";
  const component: Component<any>;
  export default component;
}
export {}
declare global {
  const ImgSet: typeof import("@shared/ImgSet.svelte").default
}
